version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
     - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    links:
      - zookeeper
    ports:
     - "9092:9092"
    expose:
     - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "satellite_msg"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    depends_on:
      - kafka
    links: 
      - kafka
  clickhouse-client:
    image: yandex/clickhouse-client
    container_name: clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
